### ISSUE TITLE
For Each syntax

### ISSUE THREAD

**Issue by Gustavo10Destroyer** [eyza-cod2/vscode-cod-gsc#10]
![image](https://github.com/user-attachments/assets/d4f815dc-a917-4f93-8e68-ca2b8d588943)

For each support key, value syntax.

**Comment by eyza-cod2** [comment]
duplicate of #4

Foreach and ternary operation are currently not supported, they will be implemented in future versions.

For what game are you coding - Aurora mod?

**Comment by Gustavo10Destroyer** [comment]
> duplicate of #4
> 
> Foreach and ternary operation are currently not supported, they will be implemented in future versions.
> 
> For what game are you coding - Aurora mod?

for T6

**Comment by Gustavo10Destroyer** [comment]
> duplicate of #4
> 
> Foreach and ternary operation are currently not supported, they will be implemented in future versions.
> 
> For what game are you coding - Aurora mod?

Look at https://github.com/xensik/gsc-tool
You can see, BO2's GSC supports ternary operators and foreach(you can also look for more tokens)
