### ISSUE TITLE
Multi-File GoTo Definition

### ISSUE THREAD

**Issue by NightwalkerLots** [eyza-cod2/vscode-cod-gsc#11]
Tried to config the settings every which way. Read docs multiple times. This just doesn't work.
The "Go To Definition" will only work if the function is defined in the same GSC file that you're currently browsing.

If there is supposed to be a way to make this work, for the love of god just have it on by default.
Will re-enable whenever that works properly, was the soul purpose I got the extension.
Either way looks good so far.

**Comment by eyza-cod2** [comment]
The "Go To Definition" should work for current file, other files in current workspace, and included workspace folders via settings.

First make sure you have resolved errors with missing files.
![image](https://github.com/user-attachments/assets/09b5111e-c45d-40aa-a6c7-f12e4bf852e2)
(file path is in red)


If your files are spread in multiple independen foldes (for exmaple you have multiple mod files), you can include the folder for file references
![image](https://raw.githubusercontent.com/eyza-cod2/vscode-cod-gsc/master/images/vscode-workspace-folder-include.gif)


Than the "Go To Definition" should work like this:
![image](https://github.com/eyza-cod2/vscode-cod-gsc/blob/master/images/vscode-function-definition.gif?raw=true)

**Comment by NightwalkerLots** [comment]
I've tried the example for doing the include at the top for the function_included example.
This doesn't work. Most of the functions in my project are not called via " :: "


![1](https://github.com/user-attachments/assets/10b64d05-6749-44f7-83f4-331ca4b24617)
![2](https://github.com/user-attachments/assets/a67f7fda-0f76-4409-ad12-e0c65325669b)

My project is a multiple-folder workspace, but all of them are in the same parent directory.
No way that I try to get these examples to work is doing it. It will only ever work if the function is defined in the same file.
It also has started to say "workspace diagnostic off" when it is on for both user and workspace. Did a restart a few times.
This 

did work but suddenly stopped. I tried to give the extension a reference to the location in a few different ways for each method in those examples. None would work.

**Comment by eyza-cod2** [comment]
Lets try again with settings reset.
In both workspace folders there is a `/.vscode/settings.json` file, delete the file in both workspace directories.

After that there should be errors again saing that some of the files are not found or that some functions are not found.

I tried to recreate your project structure and it looks like this:
![image](https://github.com/user-attachments/assets/33177286-342a-4acf-96f3-7130183c00d8)
(no error and "Go To Definition" is working)

Do you have avaible public repo with your mode? I could open the whole mod to see if there is any problem for me.

**Also make sure you have the latest version v0.1.10**

**Comment by eyza-cod2** [comment]
Does it work?

**Comment by NightwalkerLots** [comment]
I've uninstalled the extension and just went back to searching the whole
project for the function until I found the definition.
I started to step further and further back to humor even the simple things
being wrong, as well as the json, retrying backups of it, trying different
configurations of it, doing a fresh install of the extension, ect...

It started to be more trouble than it was worth for the single feature it
had that I wanted.

**Comment by eyza-cod2** [comment]
Im sorry to heard that.

There must be something specific about your vscode / system configuration that makes my extension not working.

Without your help im not able to fix it, its working fine for others.
