### ISSUE TITLE
Add setting to include search paths for scripts

### ISSUE THREAD

**Issue by ineedbots** [eyza-cod2/vscode-cod-gsc#6]
https://github.com/eyza-cod2/vscode-cod-gsc/blob/master/src/GscFiles.ts#L156

I like to work from different folders that are different then the location of my modtool scripts. It would be nice to be able to add extra search paths for the extension to look for scripts.

**Comment by eyza-cod2** [comment]
You can add any folder into your workspace and include it for file references for any workspace folder you want.
The folder might be located anywhere.
