### ISSUE TITLE
Bad syntax false negative

### ISSUE THREAD

**Issue by ineedbots** [eyza-cod2/vscode-cod-gsc#9]
![image](https://github.com/user-attachments/assets/1599f1e1-cdba-46fa-9d86-8cb7bf5e7a96)

For some reason, `anything.` doesn't trigger bad syntax.

But anything else will

![image](https://github.com/user-attachments/assets/87b2a543-57fb-4212-9367-72877cab1d66)
![image](https://github.com/user-attachments/assets/faa850c1-e2ef-4be9-b692-9b40688f1508)

**Comment by eyza-cod2** [comment]
Thats because its recognized as somevar.level.curDoF - its a valid syntax.

I guess it would be better to process it as an error, but would have to check if this syntax appears somewhere in source files

**Comment by eyza-cod2** [comment]
Added an information diagnostics when (object + function call) and (variable + structure accessor) are not on single line

![image](https://github.com/user-attachments/assets/dddd9008-436b-434e-b52e-a920f82605a4)
